import type { Metadata } from "next";
import { Instrument_Serif, Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import BottomNavigation from "@/components/BottomNavigation";

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.variable} ${manrope.variable} antialiased`}
      >
        <div className="flex items-start">
          <Sidebar />
          <BottomNavigation />
          <div className="flex-1">
            <Header />
            <main className="py-6 px-4 lg:px-16 w-full bg-[#F5F5F535] pb-16 lg:pb-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
